POM: Declare minimum Java version needed to build
More precisely in this case, it's the minimum version of Java needed for
tests to pass. As of this writing, a too-old version of Java results in
the following test failure:

Running net.imglib2.util.RealSumTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.7 sec <<< FAILURE! - in net.imglib2.util.RealSumTest
testAdd(net.imglib2.util.RealSumTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: expected:<934464.0> but was:<1000000.0>
	at net.imglib2.util.RealSumTest.testAdd(RealSumTest.java:122)

See #192 for further details.

I am not certain that the actual minimum working version is 1.8.0_45
specifically, but we know this version works, and that version 1.8.0_25
does not. There are two other Oracle releases in between: 1.8.0_31 and
1.8.0_40.

Note that this commit will not actually do anything until the parent POM
is updated to descend from org.scijava:pom-scijava-base:3.2.0 or later.
See also imglib/pom-imglib2#1.